### ISSUE TITLE
plugin dll load error

### ISSUE THREAD

**Issue by jthermiz** [fpbattaglia/PythonPlugin#1]
After successfully compiling python plugin, every plugin fails to load when running open-ephys due to a DLL error (see below snapshot). 

![dll_load_errors](https://user-images.githubusercontent.com/5800317/31324943-a5a5b28c-ac6c-11e7-8cb4-80f0638c1a60.png)

this is probably unrelated, but in order to get python plugin to compile. I needed to modify OpenEphysLib.cpp like this:

info->type = Plugin::PLUGIN_TYPE_PROCESSOR; //  updated, compiles
//info->type = Plugin::ProcessorPlugin; // original code... threw error

**Comment by fpbattaglia** [comment]
IT looks like there was some update in the main application after I last worked on this, I need to take a look, thanks for reporting it.

**Comment by jthermiz** [comment]
Thanks for looking into this. Do you know which commit this plugin was tested with?

**Comment by fpbattaglia** [comment]
It was last year, around commit 98f396b00e8da9fa89e7c5d7249e74ca9d131b78 of plugin-GUI

**Comment by jthermiz** [comment]
I checked out that commit and copied the PythonPlugin binary into the plugins folder and received a similar DLL error, but just for the PythonPlugin... not the other modules. Maybe this error is because of my system or maybe I'm doing something wrong. I'm testing on xubuntu 16.04 if that helps. 

![image](https://user-images.githubusercontent.com/5800317/31594226-81504e20-b1e8-11e7-975b-1723754a2a33.png)

**Comment by fpbattaglia** [comment]
That configuration is in use on our lab… in ubuntu 14.04 and 16.04
best Francesco

**Comment by aresjung** [comment]
I have the similar situation.
Compiling the plugin was successful, but GUI couldn't loading the plugin dll.
Here are the snapshot for this.
![plugin loading error](https://user-images.githubusercontent.com/35728780/39557437-8e07d6de-4ec2-11e8-9f09-f7dd85706533.JPG)
Xubuntu 16.04.4 runs on my system.

**Comment by Claybarn** [comment]
For future reference, these sorts of errors often happen when open ephys tries to find a function that isn't defined python side. Closing since this seems to have been resolved.
