### ISSUE TITLE
Sample rate passed to plugin startup() is NOT the data sampling rate

### ISSUE THREAD

**Issue by beOn** [fpbattaglia/PythonPlugin#10]
PythonPlugin passes the python pluginStartup function a value it pulls from its getSampleRate() method. But PythonPlugin inherits from GenericProcessor, which defines ```getSampleRate``` as:

```cpp
float GenericProcessor::getSampleRate(int) const { return getDefaultSampleRate(); }
```

and ```getDefaultSampleRate``` as:

```cpp
float GenericProcessor::getDefaultSampleRate() const { return 44100.0; }
```

... so pluginStartup always receives a sampling rate of 44100.0. Meanwhile, the ephys data actually gets sampled at 30 kHz (usually), and as far as I can tell the true sampling rate of the data that winds up the the buffer never gets over to the plugin.

I'll put together a pull request that addresses this shortly.

**Comment by Claybarn** [comment]
Still got 44100 as the sampling rate. Did it work on your end?
